# Generated by Django 3.0.3 on 2020-05-31 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200)),
                ('username', models.SlugField(max_length=300)),
                ('email', models.EmailField(max_length=200)),
                ('profile_img', models.ImageField(upload_to='profile_imgs/')),
                ('password', models.CharField(max_length=200)),
                ('city', models.CharField(blank=True, max_length=250, null=True)),
                ('state', models.CharField(blank=True, max_length=300, null=True)),
                ('qualification', models.CharField(blank=True, max_length=300, null=True)),
                ('work', models.TextField(blank=True, null=True)),
                ('reg_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
