# Generated by Django 3.0.3 on 2020-06-03 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_banner', models.ImageField(upload_to='banner_imgs/')),
                ('register_banner', models.ImageField(upload_to='banner_imgs/')),
            ],
        ),
        migrations.RemoveField(
            model_name='member',
            name='fname',
        ),
        migrations.AddField(
            model_name='member',
            name='activate_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='full_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_content', models.TextField()),
                ('post_image', models.ImageField(default='0', upload_to='post_imgs/')),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialnetwork.Member')),
            ],
        ),
    ]
