# Generated by Django 3.0.3 on 2020-06-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0003_auto_20200603_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_img',
            field=models.ImageField(blank=True, upload_to='profile_imgs/'),
        ),
    ]
