# Generated by Django 3.0.3 on 2020-06-05 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0004_auto_20200604_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendship_date', models.DateTimeField(auto_now_add=True)),
                ('friend_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friend', to='socialnetwork.Member')),
                ('member_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member', to='socialnetwork.Member')),
            ],
        ),
    ]
