# Generated by Django 3.0.3 on 2020-06-05 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0005_friends'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friends',
            options={'verbose_name_plural': 'Friends'},
        ),
    ]
