# Generated by Django 3.0.3 on 2020-06-06 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0007_friends_accept_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_time', models.DateTimeField(auto_now_add=True)),
                ('comment_status', models.BooleanField(default=True)),
                ('member_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_member', to='socialnetwork.Member')),
                ('post_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_post', to='socialnetwork.Post')),
            ],
        ),
    ]
