# Generated by Django 3.0.3 on 2020-06-06 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0009_comment_comment_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_time', models.DateTimeField(auto_now_add=True)),
                ('member_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='like_member', to='socialnetwork.Member')),
                ('post_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='like_post', to='socialnetwork.Post')),
            ],
            options={
                'verbose_name_plural': 'Likes',
            },
        ),
    ]
