# Generated by Django 3.0.3 on 2020-06-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0010_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='activate_status',
            field=models.BooleanField(default=True),
        ),
    ]
