# Generated by Django 3.0.3 on 2020-06-08 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0011_auto_20200606_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noti_content', models.CharField(max_length=300)),
                ('read_status', models.BooleanField(default=False)),
                ('member_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='socialnetwork.Member')),
                ('ref_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_ref', to='socialnetwork.Member')),
            ],
        ),
    ]
