# Generated by Django 3.0.3 on 2020-06-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0012_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='ref_id',
            field=models.IntegerField(null=True),
        ),
    ]
