# Generated by Django 3.0.3 on 2020-06-11 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0014_auto_20200609_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='receiver_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_receiver', to='socialnetwork.Member'),
        ),
    ]
